apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ssh-users-config
data:
  users.yaml: |
    users:
      {{- range .Values.sshUsers }}
      {{- range $user, $data := . }}
      - {{ $user }}:
          ssh_key: {{ $data.sshKey | quote }}
      {{- end }}
      {{- end }}