apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets", "persistentvolumeclaims"]
  verbs: ["get","apply","create", "patch", "delete", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rolebinding
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role
  apiGroup: rbac.authorization.k8s.io