apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
automountServiceAccountToken: True
imagePullSecrets:
  - name: gitlab-registry-credentials
secrets:
  - name: host-keys-secret
  - name: munge-key-secret
  - name: database-auth-secret