slurmImage: youssefbannay1/slurm:23.02-2
#youssefbannay1/slurm:23.02
clustername: "slurm-tenant-a"
login:
  service:
    type: LoadBalancer
    annotations:
#      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
#      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#      service.beta.kubernetes.io/aws-load-balancer-type: nlb
  # Deployment resource name
  name: login
  replicas: 1
  resources:  
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi

slurmd:
  # StatefulSet resource name
  name: slurmd # NB this must match NodeName= in slurm-cluster-chart/files/slurm.conf
  replicas: 1
  tolerations:
    # - effect: NoSchedule
    #   key: amd.com/gpu
    #   operator: Exists  
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
      amd.com/gpu: "0"
    limits:
      cpu: 400m
      memory: 300Mi
      amd.com/gpu: "0"  

slurmctld:
  name: slurmctld
  # NOTE: We don't include a replicas field here because
  # replicas > 1 for slurmctld needs extra Slurm config
  tolerations:
    # - effect: NoSchedule
    #   key: amd.com/gpu
    #   operator: Exists  
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1Gi

storage:
  mountPath: /home
  storageClassName: nfs
  claimName: slurm-shared-storage
  capacity: 10Gi

database:
  image: mariadb:10.10
  storage: 100Mi

# Configmap resource names
configmaps:
  slurmConf: slurm-conf-configmap
  slurmdbdConf: slurmdbd-conf-configmap
  sshdConfig: sshd-config-configmap

# Public key used for ssh access to the login node
# If let undefined, assumes you have run the provided publish-keys.sh script to publish your public key prior to deployment
sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeME8I1kYiQrU0sWMXExevqNAlSIrD4Xr5xqz96+TwL+n+XjZZ2/GtH1yeQ2bym3UhJsaT71iHcepepIBYgox1/3Z0AYQX8juyyBwDau6n6hteCjtS+e1tlXmI+Eb0gks9yCNLQaJ8ABOvqJRgF9EcJsKrtUFrJvtEljBrKtNVmB0d4IZGCY87ouBzCqo1f4iBJLlAViNO7l95UrvX8FvqLuAkB3KjPJKKe8oe8tC16slRlfW3lDKZvDCJqM1kWgawvK+ymPO4mXi4zsEBGIycz8V+Up05u8aA6c2VMX8K08DPGmzuTeHCcOk0yGX8gkARJxy0JP3sh+q0lhUGinHA58LuAJisPtcwcnLAEzWi5c3nwgkh08R6rdg4siEP4YH8r3uOxvk+uKYSRGaMeHSPHyAeHXjsKnfhahk0ETd2fn3lk9kUJiL5+YF2qcfOCunh3K6qBDzm3PNNoPSbUXmJU0PqH6K4GRupxIBNycFZvE2++TUnZrjHCzEcbv1ksDM= youssefbannay@Youssefs-MacBook-Pro.local
               ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIg1atq3pmEWEdb2njR6F0U+IrOeZZ6YgrF4DXaV3wb6Ei6nAedA0Fduy1ahflh1DUtiEVHCN+Qd/Yo9aYpux7jpYBGHblfVsr+Jm/ExHGRTjy3tyNJwvFXM7ZOnro9g2OiLxqO+D4ytNtNbIHLkWRyoZ6vCznHU72DYaRYylL6uZTL5eWEF3EMnUyyCOTFrzVPCs1oyZR0eS8bdw8MQL4eaIsyKfeRfg4RGn21lC4RDdFye6v97cc01RTyh8Lh4+mmiFJ5vtuizEyFeAm0OO5pGcJu98mRHFLDlUlef3Vu38hNhFMGKV8mxtG1G3tmrJNUOD0jINDNvgYqtaISQxPsHm8/k9IWWCyb0kQ4gsp+YaMzh80X68vrl4ws1NRxMNJlv72c6yyxsOp2G2XzXWscY2eCnasi9t4gxplehf6643quXF30mfr3JPL24lmOSiDhXiR/GP0rdGx92cGT02PXo02O6+0XKiYRGJtPWv7Nmx1NdA5TPDiTO4TCFhMf/c= youssefbannay@ip-10-255-254-37.me-central-1.compute.internal"

# Secret resource names
secrets:
  mungeKey: munge-key-secret

gres: "NodeName=slurmd-[0-9]"
#"NodeName=slurmd-[0-100] Name=gpu Type=MI210 File=/dev/dri/renderD[128-135]"