name: Release Charts

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.10.0'  # Specify the Helm version

      - name: Set up chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token

      - name: Run chart-releaser
        run: |
          cr package charts/  # Package charts in the charts/ directory
          cr upload --release-name-template "{{ .Name }}-{{ .Version }}"  # Upload to GitHub releases
          cr index --owner oicm --repo oi-slurm-helm-charts --pages-branch gh-pages  # Update index.yaml